version: "3"
services:
  web:
    image: health-server
    build: .
    container_name: health-server
    working_dir: /app
    volumes:
      - /D/Projects/health-server:/app
      - /node_modules
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    tty: true
